{{- if .Values.admissionWebhooks.conversion.enable -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "emqx-operator.fullname" . }}-conversion-patch
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "emqx-operator.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.admissionWebhooks.conversion.patch.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "emqx-operator.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "emqx-operator.patchServiceAccountName" . }}
      containers:
      - name: conversion-patch
        image: "{{ .Values.admissionWebhooks.conversion.patch.image.repository }}:{{ .Values.admissionWebhooks.conversion.patch.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - bash
        - -c
        - |
          set -x
          for r in emqxbrokers.apps.emqx.io emqxenterprises.apps.emqx.io emqxplugins.apps.emqx.io; do
            {{- if (index .Values "admissionWebhooks" "cert" "cert-manager" "enable") }}
            kubectl patch crd $r --type merge -p '
              {
                "metadata": {
                  "annotations": {
                    "cert-manager.io/inject-ca-from": "{{ .Release.Namespace }}/{{ include "emqx-operator.fullname" . }}-serving-cert"
                  }
                }
              }
            '
            {{- end }}
            kubectl patch crd $r --type merge -p '
              {
                "spec": {
                  "conversion": {
                    "strategy": "Webhook",
                    "webhook": {
                      "clientConfig": {
                        "service": {
                          "namespace": "{{ .Release.Namespace }}",
                          "name": "{{ include "emqx-operator.fullname" . }}-webhook-service",
                          "path": "/convert"
                        }
                      },
                      "conversionReviewVersions": [
                        "v1"
                      ]
                    }
                  }
                }
              }
            '
          done
        resources:
          {{- toYaml .Values.admissionWebhooks.conversion.patch.resources | nindent 12 }}
      {{- with .Values.admissionWebhooks.conversion.patch.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionWebhooks.conversion.patch.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionWebhooks.conversion.patch.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}