apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager.yaml

commonAnnotations:
  ## automatic creation and binding of EIP by ASK pod.
  k8s.aliyun.com/eci-with-eip: "true"

patches:
- target:
    kind: Deployment
    name: cert-manager-webhook
  ## resolving port conflicts
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 10251
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
      - --v=2
      - --secure-port=10251
      - --dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)
      - --dynamic-serving-ca-secret-name=cert-manager-webhook-ca
      - --dynamic-serving-dns-names=cert-manager-webhook,cert-mager-webhook.cert-manager,cert-manager-webhook.cert-manager.svc
   