# permissions for end users to edit emqxrebalances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emqxrebalance-editor-role
rules:
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxrebalances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxrebalances/status
  verbs:
  - get
