# permissions for end users to view emqxplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emqxplugin-viewer-role
rules:
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxplugins/status
  verbs:
  - get
