# permissions for end users to edit emqxbrokers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emqx-editor-role
rules:
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxbrokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxbrokers/status
  verbs:
  - get
