# permissions for end users to edit emqxenterprises.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emqxenterprise-editor-role
rules:
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxenterprises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxenterprises/status
  verbs:
  - get
