# permissions for end users to edit emqxplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emqxplugin-editor-role
rules:
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxplugins/status
  verbs:
  - get
