# permissions for end users to edit emqxapikeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: emqx-operator
    app.kubernetes.io/managed-by: kustomize
  name: emqxapikey-editor-role
rules:
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxapikeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxapikeys/status
  verbs:
  - get
