name: Deployment operator
description: "Deployment operator"
inputs:
  repository:
    description: "operator controller image repository"
    required: true
    default: "emqx/emqx-operator-controller"
  tag:
    description: "operator controller image tag"
    required: true
    default: "latest"

runs:
  using: "composite"
  steps:
  - name: Deploy operator by helm
    shell: bash
    run: |
      set -euo pipefail
      repository=$(echo ${{ inputs.repository }} | tr '[:upper:]' '[:lower:]')
      tag=$(echo ${{ inputs.tag }} | tr '/' '-')
      helm repo add jetstack https://charts.jetstack.io
      helm dependency build deploy/charts/emqx-operator
      helm install emqx-operator deploy/charts/emqx-operator\
        --set image.repository=$repository \
        --set image.tag=$tag \
        --namespace emqx-operator-system \
        --create-namespace
  - name: Check operator
    shell: bash
    run: |
      set -euo pipefail
      kubectl wait --for=condition=Ready pods -l "control-plane=controller-manager" -n emqx-operator-system --timeout=60s