apiVersion: v1
kind: Service
metadata:
  name: emqx-lb
  namespace: default
spec:
  selector:
     cluster: emqx
  ports:
    - name: tcp
      port: 1883
      protocol: TCP
      targetPort: 1883
    - name: tcps
      port: 8883
      protocol: TCP
      targetPort: 8883
    - name: ws
      port: 8083
      protocol: TCP
      targetPort: 8083
    - name: wss
      port: 8084
      protocol: TCP
      targetPort: 8084
    - name: dashboard
      port: 18083
      protocol: TCP
      targetPort: 18083
  type: NodePort
