apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqx

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emqx
rules:
- apiGroups: 
  - ""
  resources:
  - endpoints
  verbs:
    - "*"
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxbrokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxbrokers/finalizers
  verbs:
  - update
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxbrokers/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: emqx-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: emqx
subjects:
- kind: ServiceAccount
  name: emqx
  namespace: default
