// Code generated by pigeon; DO NOT EDIT.

package hocon

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

func toAnySlice(v any) []any {
	if v == nil {
		return nil
	}
	return v.([]any)
}

func validatePath(path any) error {
	components := asPath(path.(string))
	if len(components) == 0 {
		return ErrInvalidPath
	}
	return nil
}

func validatePartials(ps partials) error {
	ty := fragmentIndeterminate
	for _, p := range ps {
		if p.fragType() == fragmentIndeterminate {
			continue
		}
		if p.fragType() == ty {
			continue
		}
		if ty == fragmentIndeterminate {
			ty = p.fragType()
			continue
		}
		return ErrMixedPartials
	}
	return nil
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Root",
			pos:  position{line: 45, col: 1, offset: 725},
			expr: &actionExpr{
				pos: position{line: 45, col: 8, offset: 734},
				run: (*parser).callonRoot1,
				expr: &seqExpr{
					pos: position{line: 45, col: 8, offset: 734},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 45, col: 8, offset: 734},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 45, col: 10, offset: 736},
							label: "ps",
							expr: &choiceExpr{
								pos: position{line: 45, col: 15, offset: 741},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 45, col: 15, offset: 741},
										name: "Object",
									},
									&ruleRefExpr{
										pos:  position{line: 45, col: 24, offset: 750},
										name: "Properties",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 37, offset: 763},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 39, offset: 765},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 49, col: 1, offset: 793},
			expr: &actionExpr{
				pos: position{line: 49, col: 9, offset: 803},
				run: (*parser).callonValue1,
				expr: &labeledExpr{
					pos:   position{line: 49, col: 9, offset: 803},
					label: "v",
					expr: &choiceExpr{
						pos: position{line: 49, col: 13, offset: 807},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 49, col: 13, offset: 807},
								name: "Percent",
							},
							&ruleRefExpr{
								pos:  position{line: 49, col: 23, offset: 817},
								name: "Bytesize",
							},
							&ruleRefExpr{
								pos:  position{line: 49, col: 34, offset: 828},
								name: "Duration",
							},
							&ruleRefExpr{
								pos:  position{line: 49, col: 45, offset: 839},
								name: "Float",
							},
							&ruleRefExpr{
								pos:  position{line: 49, col: 53, offset: 847},
								name: "Integer",
							},
							&ruleRefExpr{
								pos:  position{line: 49, col: 63, offset: 857},
								name: "Bool",
							},
							&ruleRefExpr{
								pos:  position{line: 49, col: 70, offset: 864},
								name: "Null",
							},
							&ruleRefExpr{
								pos:  position{line: 49, col: 77, offset: 871},
								name: "Partials",
							},
							&ruleRefExpr{
								pos:  position{line: 49, col: 88, offset: 882},
								name: "Reference",
							},
						},
					},
				},
			},
		},
		{
			name: "Partials",
			pos:  position{line: 53, col: 1, offset: 929},
			expr: &actionExpr{
				pos: position{line: 53, col: 12, offset: 942},
				run: (*parser).callonPartials1,
				expr: &seqExpr{
					pos: position{line: 53, col: 12, offset: 942},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 53, col: 12, offset: 942},
							label: "v",
							expr: &ruleRefExpr{
								pos:  position{line: 53, col: 14, offset: 944},
								name: "Partial",
							},
						},
						&labeledExpr{
							pos:   position{line: 53, col: 22, offset: 952},
							label: "vs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 53, col: 25, offset: 955},
								expr: &seqExpr{
									pos: position{line: 53, col: 27, offset: 957},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 53, col: 27, offset: 957},
											name: "WSLine",
										},
										&ruleRefExpr{
											pos:  position{line: 53, col: 34, offset: 964},
											name: "Partial",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Partial",
			pos:  position{line: 62, col: 1, offset: 1165},
			expr: &actionExpr{
				pos: position{line: 62, col: 11, offset: 1177},
				run: (*parser).callonPartial1,
				expr: &labeledExpr{
					pos:   position{line: 62, col: 11, offset: 1177},
					label: "v",
					expr: &choiceExpr{
						pos: position{line: 62, col: 15, offset: 1181},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 62, col: 15, offset: 1181},
								name: "Object",
							},
							&ruleRefExpr{
								pos:  position{line: 62, col: 24, offset: 1190},
								name: "Array",
							},
							&ruleRefExpr{
								pos:  position{line: 62, col: 32, offset: 1198},
								name: "Reference",
							},
							&ruleRefExpr{
								pos:  position{line: 62, col: 44, offset: 1210},
								name: "String",
							},
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 66, col: 1, offset: 1263},
			expr: &actionExpr{
				pos: position{line: 66, col: 10, offset: 1274},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 66, col: 10, offset: 1274},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 66, col: 10, offset: 1274},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 66, col: 14, offset: 1278},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 66, col: 16, offset: 1280},
							label: "ps",
							expr: &ruleRefExpr{
								pos:  position{line: 66, col: 19, offset: 1283},
								name: "Properties",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 66, col: 30, offset: 1294},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 66, col: 32, offset: 1296},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "Properties",
			pos:  position{line: 70, col: 1, offset: 1324},
			expr: &actionExpr{
				pos: position{line: 70, col: 14, offset: 1339},
				run: (*parser).callonProperties1,
				expr: &labeledExpr{
					pos:   position{line: 70, col: 14, offset: 1339},
					label: "ps",
					expr: &zeroOrOneExpr{
						pos: position{line: 70, col: 17, offset: 1342},
						expr: &seqExpr{
							pos: position{line: 70, col: 19, offset: 1344},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 70, col: 19, offset: 1344},
									name: "Entry",
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 25, offset: 1350},
									name: "_",
								},
								&zeroOrOneExpr{
									pos: position{line: 70, col: 27, offset: 1352},
									expr: &litMatcher{
										pos:        position{line: 70, col: 27, offset: 1352},
										val:        ",",
										ignoreCase: false,
										want:       "\",\"",
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 70, col: 32, offset: 1357},
									expr: &seqExpr{
										pos: position{line: 70, col: 34, offset: 1359},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 70, col: 34, offset: 1359},
												name: "_",
											},
											&ruleRefExpr{
												pos:  position{line: 70, col: 36, offset: 1361},
												name: "Entry",
											},
											&ruleRefExpr{
												pos:  position{line: 70, col: 42, offset: 1367},
												name: "_",
											},
											&zeroOrOneExpr{
												pos: position{line: 70, col: 44, offset: 1369},
												expr: &litMatcher{
													pos:        position{line: 70, col: 44, offset: 1369},
													val:        ",",
													ignoreCase: false,
													want:       "\",\"",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Entry",
			pos:  position{line: 84, col: 1, offset: 1674},
			expr: &choiceExpr{
				pos: position{line: 85, col: 7, offset: 1690},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 85, col: 7, offset: 1690},
						run: (*parser).callonEntry2,
						expr: &labeledExpr{
							pos:   position{line: 85, col: 7, offset: 1690},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 9, offset: 1692},
								name: "Include",
							},
						},
					},
					&actionExpr{
						pos: position{line: 86, col: 7, offset: 1724},
						run: (*parser).callonEntry5,
						expr: &labeledExpr{
							pos:   position{line: 86, col: 7, offset: 1724},
							label: "p",
							expr: &ruleRefExpr{
								pos:  position{line: 86, col: 9, offset: 1726},
								name: "Property",
							},
						},
					},
				},
			},
		},
		{
			name: "Include",
			pos:  position{line: 88, col: 1, offset: 1754},
			expr: &actionExpr{
				pos: position{line: 88, col: 11, offset: 1766},
				run: (*parser).callonInclude1,
				expr: &seqExpr{
					pos: position{line: 88, col: 11, offset: 1766},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 88, col: 11, offset: 1766},
							val:        "include",
							ignoreCase: false,
							want:       "\"include\"",
						},
						&ruleRefExpr{
							pos:  position{line: 88, col: 21, offset: 1776},
							name: "WS",
						},
						&ruleRefExpr{
							pos:  position{line: 88, col: 24, offset: 1779},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 88, col: 26, offset: 1781},
							label: "inc",
							expr: &choiceExpr{
								pos: position{line: 88, col: 32, offset: 1787},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 88, col: 32, offset: 1787},
										name: "RequiredInclude",
									},
									&ruleRefExpr{
										pos:  position{line: 88, col: 50, offset: 1805},
										name: "OptionalInclude",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "RequiredInclude",
			pos:  position{line: 92, col: 1, offset: 1848},
			expr: &actionExpr{
				pos: position{line: 92, col: 19, offset: 1868},
				run: (*parser).callonRequiredInclude1,
				expr: &seqExpr{
					pos: position{line: 92, col: 19, offset: 1868},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 92, col: 19, offset: 1868},
							val:        "required",
							ignoreCase: false,
							want:       "\"required\"",
						},
						&ruleRefExpr{
							pos:  position{line: 92, col: 30, offset: 1879},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 92, col: 32, offset: 1881},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 92, col: 36, offset: 1885},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 92, col: 38, offset: 1887},
							label: "target",
							expr: &ruleRefExpr{
								pos:  position{line: 92, col: 45, offset: 1894},
								name: "StringQuoted",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 92, col: 58, offset: 1907},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 92, col: 60, offset: 1909},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "OptionalInclude",
			pos:  position{line: 96, col: 1, offset: 1995},
			expr: &actionExpr{
				pos: position{line: 96, col: 19, offset: 2015},
				run: (*parser).callonOptionalInclude1,
				expr: &labeledExpr{
					pos:   position{line: 96, col: 19, offset: 2015},
					label: "target",
					expr: &ruleRefExpr{
						pos:  position{line: 96, col: 26, offset: 2022},
						name: "StringQuoted",
					},
				},
			},
		},
		{
			name: "Property",
			pos:  position{line: 100, col: 1, offset: 2101},
			expr: &choiceExpr{
				pos: position{line: 101, col: 7, offset: 2120},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 101, col: 7, offset: 2120},
						run: (*parser).callonProperty2,
						expr: &seqExpr{
							pos: position{line: 101, col: 7, offset: 2120},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 101, col: 7, offset: 2120},
									label: "path",
									expr: &ruleRefExpr{
										pos:  position{line: 101, col: 12, offset: 2125},
										name: "Ident",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 101, col: 18, offset: 2131},
									name: "_",
								},
								&charClassMatcher{
									pos:        position{line: 101, col: 20, offset: 2133},
									val:        "[:=]",
									chars:      []rune{':', '='},
									ignoreCase: false,
									inverted:   false,
								},
								&ruleRefExpr{
									pos:  position{line: 101, col: 25, offset: 2138},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 101, col: 27, offset: 2140},
									label: "v",
									expr: &ruleRefExpr{
										pos:  position{line: 101, col: 29, offset: 2142},
										name: "Value",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 102, col: 7, offset: 2212},
						run: (*parser).callonProperty11,
						expr: &seqExpr{
							pos: position{line: 102, col: 7, offset: 2212},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 102, col: 7, offset: 2212},
									label: "path",
									expr: &ruleRefExpr{
										pos:  position{line: 102, col: 12, offset: 2217},
										name: "Ident",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 102, col: 18, offset: 2223},
									name: "_",
								},
								&andExpr{
									pos: position{line: 102, col: 20, offset: 2225},
									expr: &litMatcher{
										pos:        position{line: 102, col: 21, offset: 2226},
										val:        "{",
										ignoreCase: false,
										want:       "\"{\"",
									},
								},
								&labeledExpr{
									pos:   position{line: 102, col: 25, offset: 2230},
									label: "v",
									expr: &ruleRefExpr{
										pos:  position{line: 102, col: 27, offset: 2232},
										name: "Partials",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Array",
			pos:  position{line: 104, col: 1, offset: 2300},
			expr: &actionExpr{
				pos: position{line: 104, col: 9, offset: 2310},
				run: (*parser).callonArray1,
				expr: &seqExpr{
					pos: position{line: 104, col: 9, offset: 2310},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 104, col: 9, offset: 2310},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 104, col: 13, offset: 2314},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 104, col: 15, offset: 2316},
							label: "vs",
							expr: &zeroOrOneExpr{
								pos: position{line: 104, col: 18, offset: 2319},
								expr: &seqExpr{
									pos: position{line: 104, col: 20, offset: 2321},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 104, col: 20, offset: 2321},
											name: "Value",
										},
										&ruleRefExpr{
											pos:  position{line: 104, col: 26, offset: 2327},
											name: "_",
										},
										&zeroOrOneExpr{
											pos: position{line: 104, col: 28, offset: 2329},
											expr: &litMatcher{
												pos:        position{line: 104, col: 28, offset: 2329},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
										},
										&zeroOrMoreExpr{
											pos: position{line: 104, col: 33, offset: 2334},
											expr: &seqExpr{
												pos: position{line: 104, col: 35, offset: 2336},
												exprs: []any{
													&ruleRefExpr{
														pos:  position{line: 104, col: 35, offset: 2336},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 104, col: 37, offset: 2338},
														name: "Value",
													},
													&ruleRefExpr{
														pos:  position{line: 104, col: 43, offset: 2344},
														name: "_",
													},
													&zeroOrOneExpr{
														pos: position{line: 104, col: 45, offset: 2346},
														expr: &litMatcher{
															pos:        position{line: 104, col: 45, offset: 2346},
															val:        ",",
															ignoreCase: false,
															want:       "\",\"",
														},
													},
												},
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 104, col: 56, offset: 2357},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 104, col: 58, offset: 2359},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "Percent",
			pos:  position{line: 117, col: 1, offset: 2636},
			expr: &actionExpr{
				pos: position{line: 117, col: 11, offset: 2648},
				run: (*parser).callonPercent1,
				expr: &seqExpr{
					pos: position{line: 117, col: 11, offset: 2648},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 117, col: 11, offset: 2648},
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 11, offset: 2648},
								name: "DecimalDigit",
							},
						},
						&litMatcher{
							pos:        position{line: 117, col: 25, offset: 2662},
							val:        "%",
							ignoreCase: false,
							want:       "\"%\"",
						},
					},
				},
			},
		},
		{
			name: "Bytesize",
			pos:  position{line: 121, col: 1, offset: 2703},
			expr: &actionExpr{
				pos: position{line: 121, col: 12, offset: 2716},
				run: (*parser).callonBytesize1,
				expr: &seqExpr{
					pos: position{line: 121, col: 12, offset: 2716},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 121, col: 12, offset: 2716},
							expr: &ruleRefExpr{
								pos:  position{line: 121, col: 12, offset: 2716},
								name: "DecimalDigit",
							},
						},
						&choiceExpr{
							pos: position{line: 121, col: 28, offset: 2732},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 121, col: 28, offset: 2732},
									val:        "kb",
									ignoreCase: false,
									want:       "\"kb\"",
								},
								&litMatcher{
									pos:        position{line: 121, col: 35, offset: 2739},
									val:        "KB",
									ignoreCase: false,
									want:       "\"KB\"",
								},
								&litMatcher{
									pos:        position{line: 121, col: 42, offset: 2746},
									val:        "mb",
									ignoreCase: false,
									want:       "\"mb\"",
								},
								&litMatcher{
									pos:        position{line: 121, col: 49, offset: 2753},
									val:        "MB",
									ignoreCase: false,
									want:       "\"MB\"",
								},
								&litMatcher{
									pos:        position{line: 121, col: 56, offset: 2760},
									val:        "gb",
									ignoreCase: false,
									want:       "\"gb\"",
								},
								&litMatcher{
									pos:        position{line: 121, col: 63, offset: 2767},
									val:        "GB",
									ignoreCase: false,
									want:       "\"GB\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Duration",
			pos:  position{line: 125, col: 1, offset: 2812},
			expr: &actionExpr{
				pos: position{line: 125, col: 12, offset: 2825},
				run: (*parser).callonDuration1,
				expr: &seqExpr{
					pos: position{line: 125, col: 12, offset: 2825},
					exprs: []any{
						&oneOrMoreExpr{
							pos: position{line: 125, col: 12, offset: 2825},
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 12, offset: 2825},
								name: "DecimalDigit",
							},
						},
						&choiceExpr{
							pos: position{line: 125, col: 28, offset: 2841},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 125, col: 28, offset: 2841},
									val:        "ms",
									ignoreCase: false,
									want:       "\"ms\"",
								},
								&litMatcher{
									pos:        position{line: 125, col: 35, offset: 2848},
									val:        "MS",
									ignoreCase: false,
									want:       "\"MS\"",
								},
								&litMatcher{
									pos:        position{line: 125, col: 42, offset: 2855},
									val:        "d",
									ignoreCase: false,
									want:       "\"d\"",
								},
								&litMatcher{
									pos:        position{line: 125, col: 48, offset: 2861},
									val:        "D",
									ignoreCase: false,
									want:       "\"D\"",
								},
								&litMatcher{
									pos:        position{line: 125, col: 54, offset: 2867},
									val:        "h",
									ignoreCase: false,
									want:       "\"h\"",
								},
								&litMatcher{
									pos:        position{line: 125, col: 60, offset: 2873},
									val:        "H",
									ignoreCase: false,
									want:       "\"H\"",
								},
								&litMatcher{
									pos:        position{line: 125, col: 66, offset: 2879},
									val:        "m",
									ignoreCase: false,
									want:       "\"m\"",
								},
								&litMatcher{
									pos:        position{line: 125, col: 72, offset: 2885},
									val:        "M",
									ignoreCase: false,
									want:       "\"M\"",
								},
								&litMatcher{
									pos:        position{line: 125, col: 78, offset: 2891},
									val:        "s",
									ignoreCase: false,
									want:       "\"s\"",
								},
								&litMatcher{
									pos:        position{line: 125, col: 84, offset: 2897},
									val:        "S",
									ignoreCase: false,
									want:       "\"S\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Float",
			pos:  position{line: 129, col: 1, offset: 2941},
			expr: &actionExpr{
				pos: position{line: 129, col: 9, offset: 2951},
				run: (*parser).callonFloat1,
				expr: &seqExpr{
					pos: position{line: 129, col: 9, offset: 2951},
					exprs: []any{
						&zeroOrOneExpr{
							pos: position{line: 129, col: 9, offset: 2951},
							expr: &charClassMatcher{
								pos:        position{line: 129, col: 9, offset: 2951},
								val:        "[+-]",
								chars:      []rune{'+', '-'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 129, col: 15, offset: 2957},
							name: "Integer",
						},
						&litMatcher{
							pos:        position{line: 129, col: 23, offset: 2965},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&oneOrMoreExpr{
							pos: position{line: 129, col: 27, offset: 2969},
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 27, offset: 2969},
								name: "DecimalDigit",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 129, col: 41, offset: 2983},
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 41, offset: 2983},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 133, col: 1, offset: 3048},
			expr: &seqExpr{
				pos: position{line: 133, col: 12, offset: 3061},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 133, col: 12, offset: 3061},
						val:        "e",
						ignoreCase: true,
						want:       "\"e\"i",
					},
					&zeroOrOneExpr{
						pos: position{line: 133, col: 17, offset: 3066},
						expr: &charClassMatcher{
							pos:        position{line: 133, col: 17, offset: 3066},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 133, col: 23, offset: 3072},
						expr: &ruleRefExpr{
							pos:  position{line: 133, col: 23, offset: 3072},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 135, col: 1, offset: 3087},
			expr: &actionExpr{
				pos: position{line: 135, col: 11, offset: 3099},
				run: (*parser).callonInteger1,
				expr: &choiceExpr{
					pos: position{line: 135, col: 13, offset: 3101},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 135, col: 13, offset: 3101},
							val:        "0",
							ignoreCase: false,
							want:       "\"0\"",
						},
						&seqExpr{
							pos: position{line: 135, col: 19, offset: 3107},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 135, col: 19, offset: 3107},
									name: "NonZeroDecimalDigit",
								},
								&zeroOrMoreExpr{
									pos: position{line: 135, col: 39, offset: 3127},
									expr: &ruleRefExpr{
										pos:  position{line: 135, col: 39, offset: 3127},
										name: "DecimalDigit",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 139, col: 1, offset: 3200},
			expr: &charClassMatcher{
				pos:        position{line: 139, col: 23, offset: 3224},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 140, col: 1, offset: 3230},
			expr: &charClassMatcher{
				pos:        position{line: 140, col: 16, offset: 3247},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Ident",
			pos:  position{line: 142, col: 1, offset: 3254},
			expr: &choiceExpr{
				pos: position{line: 143, col: 7, offset: 3270},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 143, col: 7, offset: 3270},
						run: (*parser).callonIdent2,
						expr: &labeledExpr{
							pos:   position{line: 143, col: 7, offset: 3270},
							label: "slit",
							expr: &ruleRefExpr{
								pos:  position{line: 143, col: 12, offset: 3275},
								name: "StringUnquoted",
							},
						},
					},
					&actionExpr{
						pos: position{line: 144, col: 7, offset: 3340},
						run: (*parser).callonIdent5,
						expr: &labeledExpr{
							pos:   position{line: 144, col: 7, offset: 3340},
							label: "slit",
							expr: &ruleRefExpr{
								pos:  position{line: 144, col: 12, offset: 3345},
								name: "StringTripleQuoted",
							},
						},
					},
					&actionExpr{
						pos: position{line: 145, col: 7, offset: 3412},
						run: (*parser).callonIdent8,
						expr: &labeledExpr{
							pos:   position{line: 145, col: 7, offset: 3412},
							label: "slit",
							expr: &ruleRefExpr{
								pos:  position{line: 145, col: 12, offset: 3417},
								name: "StringQuoted",
							},
						},
					},
				},
			},
		},
		{
			name: "IdentUnquoted",
			pos:  position{line: 147, col: 1, offset: 3479},
			expr: &actionExpr{
				pos: position{line: 147, col: 17, offset: 3497},
				run: (*parser).callonIdentUnquoted1,
				expr: &ruleRefExpr{
					pos:  position{line: 147, col: 17, offset: 3497},
					name: "StringUnquoted",
				},
			},
		},
		{
			name: "Reference",
			pos:  position{line: 151, col: 1, offset: 3548},
			expr: &actionExpr{
				pos: position{line: 151, col: 13, offset: 3562},
				run: (*parser).callonReference1,
				expr: &seqExpr{
					pos: position{line: 151, col: 13, offset: 3562},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 151, col: 13, offset: 3562},
							val:        "$",
							ignoreCase: false,
							want:       "\"$\"",
						},
						&litMatcher{
							pos:        position{line: 151, col: 17, offset: 3566},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&labeledExpr{
							pos:   position{line: 151, col: 21, offset: 3570},
							label: "opt",
							expr: &zeroOrOneExpr{
								pos: position{line: 151, col: 25, offset: 3574},
								expr: &litMatcher{
									pos:        position{line: 151, col: 25, offset: 3574},
									val:        "?",
									ignoreCase: false,
									want:       "\"?\"",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 151, col: 30, offset: 3579},
							label: "path",
							expr: &ruleRefExpr{
								pos:  position{line: 151, col: 35, offset: 3584},
								name: "IdentUnquoted",
							},
						},
						&litMatcher{
							pos:        position{line: 151, col: 49, offset: 3598},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 156, col: 1, offset: 3714},
			expr: &actionExpr{
				pos: position{line: 156, col: 10, offset: 3725},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 156, col: 10, offset: 3725},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 156, col: 10, offset: 3725},
							label: "s",
							expr: &choiceExpr{
								pos: position{line: 156, col: 14, offset: 3729},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 156, col: 14, offset: 3729},
										name: "StringUnquoted",
									},
									&ruleRefExpr{
										pos:  position{line: 156, col: 31, offset: 3746},
										name: "StringTripleQuoted",
									},
									&ruleRefExpr{
										pos:  position{line: 156, col: 52, offset: 3767},
										name: "StringQuoted",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 156, col: 67, offset: 3782},
							name: "_",
						},
						&notExpr{
							pos: position{line: 156, col: 69, offset: 3784},
							expr: &charClassMatcher{
								pos:        position{line: 156, col: 70, offset: 3785},
								val:        "[:={]",
								chars:      []rune{':', '=', '{'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "StringUnquoted",
			pos:  position{line: 160, col: 1, offset: 3814},
			expr: &actionExpr{
				pos: position{line: 160, col: 18, offset: 3833},
				run: (*parser).callonStringUnquoted1,
				expr: &seqExpr{
					pos: position{line: 160, col: 18, offset: 3833},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 160, col: 18, offset: 3833},
							val:        "[a-z]i",
							ranges:     []rune{'a', 'z'},
							ignoreCase: true,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 160, col: 25, offset: 3840},
							expr: &charClassMatcher{
								pos:        position{line: 160, col: 25, offset: 3840},
								val:        "[a-z0-9_.@%-]i",
								chars:      []rune{'_', '.', '@', '%', '-'},
								ranges:     []rune{'a', 'z', '0', '9'},
								ignoreCase: true,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "StringQuoted",
			pos:  position{line: 165, col: 1, offset: 3935},
			expr: &actionExpr{
				pos: position{line: 165, col: 16, offset: 3952},
				run: (*parser).callonStringQuoted1,
				expr: &seqExpr{
					pos: position{line: 165, col: 16, offset: 3952},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 165, col: 16, offset: 3952},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 165, col: 20, offset: 3956},
							expr: &choiceExpr{
								pos: position{line: 165, col: 22, offset: 3958},
								alternatives: []any{
									&seqExpr{
										pos: position{line: 165, col: 22, offset: 3958},
										exprs: []any{
											&notExpr{
												pos: position{line: 165, col: 22, offset: 3958},
												expr: &ruleRefExpr{
													pos:  position{line: 165, col: 23, offset: 3959},
													name: "CharNeedEscape",
												},
											},
											&anyMatcher{
												line: 165, col: 38, offset: 3974,
											},
										},
									},
									&seqExpr{
										pos: position{line: 165, col: 42, offset: 3978},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 165, col: 42, offset: 3978},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 165, col: 47, offset: 3983},
												name: "SingleCharEscape",
											},
										},
									},
									&seqExpr{
										pos: position{line: 165, col: 66, offset: 4002},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 165, col: 66, offset: 4002},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 165, col: 71, offset: 4007},
												name: "UnicodeEscape",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 165, col: 88, offset: 4024},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "StringTripleQuoted",
			pos:  position{line: 170, col: 1, offset: 4127},
			expr: &actionExpr{
				pos: position{line: 170, col: 22, offset: 4150},
				run: (*parser).callonStringTripleQuoted1,
				expr: &seqExpr{
					pos: position{line: 170, col: 22, offset: 4150},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 170, col: 22, offset: 4150},
							name: "TripleQuote",
						},
						&zeroOrMoreExpr{
							pos: position{line: 170, col: 34, offset: 4162},
							expr: &seqExpr{
								pos: position{line: 170, col: 36, offset: 4164},
								exprs: []any{
									&notExpr{
										pos: position{line: 170, col: 36, offset: 4164},
										expr: &ruleRefExpr{
											pos:  position{line: 170, col: 37, offset: 4165},
											name: "TripleQuote",
										},
									},
									&anyMatcher{
										line: 170, col: 49, offset: 4177,
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 170, col: 54, offset: 4182},
							name: "TripleQuote",
						},
					},
				},
			},
		},
		{
			name: "CharNeedEscape",
			pos:  position{line: 175, col: 1, offset: 4323},
			expr: &charClassMatcher{
				pos:        position{line: 175, col: 18, offset: 4342},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 177, col: 1, offset: 4358},
			expr: &charClassMatcher{
				pos:        position{line: 177, col: 20, offset: 4379},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 178, col: 1, offset: 4391},
			expr: &seqExpr{
				pos: position{line: 178, col: 17, offset: 4409},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 178, col: 17, offset: 4409},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 178, col: 21, offset: 4413},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 178, col: 30, offset: 4422},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 178, col: 39, offset: 4431},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 178, col: 48, offset: 4440},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 180, col: 1, offset: 4450},
			expr: &charClassMatcher{
				pos:        position{line: 180, col: 12, offset: 4463},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "TripleQuote",
			pos:  position{line: 182, col: 1, offset: 4474},
			expr: &seqExpr{
				pos: position{line: 182, col: 15, offset: 4490},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 182, col: 15, offset: 4490},
						val:        "\"",
						ignoreCase: false,
						want:       "\"\\\"\"",
					},
					&litMatcher{
						pos:        position{line: 182, col: 19, offset: 4494},
						val:        "\"",
						ignoreCase: false,
						want:       "\"\\\"\"",
					},
					&litMatcher{
						pos:        position{line: 182, col: 23, offset: 4498},
						val:        "\"",
						ignoreCase: false,
						want:       "\"\\\"\"",
					},
				},
			},
		},
		{
			name: "Bool",
			pos:  position{line: 184, col: 1, offset: 4503},
			expr: &choiceExpr{
				pos: position{line: 184, col: 8, offset: 4512},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 184, col: 8, offset: 4512},
						run: (*parser).callonBool2,
						expr: &litMatcher{
							pos:        position{line: 184, col: 8, offset: 4512},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 184, col: 38, offset: 4542},
						run: (*parser).callonBool4,
						expr: &litMatcher{
							pos:        position{line: 184, col: 38, offset: 4542},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 186, col: 1, offset: 4573},
			expr: &actionExpr{
				pos: position{line: 186, col: 8, offset: 4582},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 186, col: 8, offset: 4582},
					val:        "null",
					ignoreCase: false,
					want:       "\"null\"",
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace or comments\"",
			pos:         position{line: 188, col: 1, offset: 4610},
			expr: &zeroOrMoreExpr{
				pos: position{line: 188, col: 30, offset: 4641},
				expr: &choiceExpr{
					pos: position{line: 188, col: 32, offset: 4643},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 188, col: 32, offset: 4643},
							name: "Comment",
						},
						&ruleRefExpr{
							pos:  position{line: 188, col: 42, offset: 4653},
							name: "WS",
						},
					},
				},
			},
		},
		{
			name:        "WSLine",
			displayName: "\"non-line-breaking whitespace\"",
			pos:         position{line: 190, col: 1, offset: 4660},
			expr: &zeroOrMoreExpr{
				pos: position{line: 190, col: 41, offset: 4702},
				expr: &ruleRefExpr{
					pos:  position{line: 190, col: 41, offset: 4702},
					name: "WSNoLinebreak",
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 191, col: 1, offset: 4717},
			expr: &seqExpr{
				pos: position{line: 191, col: 11, offset: 4729},
				exprs: []any{
					&choiceExpr{
						pos: position{line: 191, col: 13, offset: 4731},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 191, col: 13, offset: 4731},
								val:        "#",
								ignoreCase: false,
								want:       "\"#\"",
							},
							&litMatcher{
								pos:        position{line: 191, col: 19, offset: 4737},
								val:        "//",
								ignoreCase: false,
								want:       "\"//\"",
							},
						},
					},
					&zeroOrMoreExpr{
						pos: position{line: 191, col: 26, offset: 4744},
						expr: &seqExpr{
							pos: position{line: 191, col: 28, offset: 4746},
							exprs: []any{
								&notExpr{
									pos: position{line: 191, col: 28, offset: 4746},
									expr: &ruleRefExpr{
										pos:  position{line: 191, col: 29, offset: 4747},
										name: "Linebreak",
									},
								},
								&anyMatcher{
									line: 191, col: 39, offset: 4757,
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 191, col: 44, offset: 4762},
						name: "Linebreak",
					},
				},
			},
		},
		{
			name: "WS",
			pos:  position{line: 193, col: 1, offset: 4773},
			expr: &charClassMatcher{
				pos:        position{line: 193, col: 6, offset: 4780},
				val:        "[ \\t\\v\\f\\r\\n\\u2028\\u2029]",
				chars:      []rune{' ', '\t', '\v', '\f', '\r', '\n', '\u2028', '\u2029'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "WSNoLinebreak",
			pos:  position{line: 194, col: 1, offset: 4806},
			expr: &charClassMatcher{
				pos:        position{line: 194, col: 17, offset: 4824},
				val:        "[ \\t\\v\\f]",
				chars:      []rune{' ', '\t', '\v', '\f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Linebreak",
			pos:  position{line: 195, col: 1, offset: 4834},
			expr: &charClassMatcher{
				pos:        position{line: 195, col: 13, offset: 4848},
				val:        "[\\r\\n\\u2028\\u2029]",
				chars:      []rune{'\r', '\n', '\u2028', '\u2029'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 197, col: 1, offset: 4868},
			expr: &notExpr{
				pos: position{line: 197, col: 7, offset: 4876},
				expr: &anyMatcher{
					line: 197, col: 8, offset: 4877,
				},
			},
		},
	},
}

func (c *current) onRoot1(ps any) (any, error) {
	return ps, nil
}

func (p *parser) callonRoot1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRoot1(stack["ps"])
}

func (c *current) onValue1(v any) (any, error) {
	return parseValue(v), nil
}

func (p *parser) callonValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["v"])
}

func (c *current) onPartials1(v, vs any) (any, error) {
	out := partials{v.(partial)}
	for _, v := range toAnySlice(vs) {
		p := toAnySlice(v)[1]
		out = append(out, p.(partial))
	}
	return out, validatePartials(out)
}

func (p *parser) callonPartials1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPartials1(stack["v"], stack["vs"])
}

func (c *current) onPartial1(v any) (any, error) {
	return partial{v.(parseNode)}, nil
}

func (p *parser) callonPartial1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPartial1(stack["v"])
}

func (c *current) onObject1(ps any) (any, error) {
	return ps, nil
}

func (p *parser) callonObject1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["ps"])
}

func (c *current) onProperties1(ps any) (any, error) {
	out := propertyList{}
	psSlice := toAnySlice(ps)
	if len(psSlice) == 0 {
		return out, nil
	}
	out = append(out, psSlice[0])
	for _, v := range toAnySlice(psSlice[3]) {
		vSlice := toAnySlice(v)
		out = append(out, vSlice[1])
	}
	return out, nil
}

func (p *parser) callonProperties1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProperties1(stack["ps"])
}

func (c *current) onEntry2(i any) (any, error) {
	return i, nil
}

func (p *parser) callonEntry2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEntry2(stack["i"])
}

func (c *current) onEntry5(p any) (any, error) {
	return p, nil
}

func (p *parser) callonEntry5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEntry5(stack["p"])
}

func (c *current) onInclude1(inc any) (any, error) {
	return inc, nil
}

func (p *parser) callonInclude1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInclude1(stack["inc"])
}

func (c *current) onRequiredInclude1(target any) (any, error) {
	return includeOf{path: target.(stringLit).string(), required: true}, nil
}

func (p *parser) callonRequiredInclude1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRequiredInclude1(stack["target"])
}

func (c *current) onOptionalInclude1(target any) (any, error) {
	return includeOf{path: target.(stringLit).string()}, nil
}

func (p *parser) callonOptionalInclude1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionalInclude1(stack["target"])
}

func (c *current) onProperty2(path, v any) (any, error) {
	return property{path.(string), v}, validatePath(path)
}

func (p *parser) callonProperty2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProperty2(stack["path"], stack["v"])
}

func (c *current) onProperty11(path, v any) (any, error) {
	return property{path.(string), v}, validatePath(path)
}

func (p *parser) callonProperty11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProperty11(stack["path"], stack["v"])
}

func (c *current) onArray1(vs any) (any, error) {
	vsSlice := toAnySlice(vs)
	if len(vsSlice) == 0 {
		return nodeList{}, nil
	}
	out := nodeList{vsSlice[0]}
	for _, v := range toAnySlice(vsSlice[3]) {
		vSlice := toAnySlice(v)
		out = append(out, vSlice[1])
	}
	return out, nil
}

func (p *parser) callonArray1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray1(stack["vs"])
}

func (c *current) onPercent1() (any, error) {
	return percent(c.text), nil
}

func (p *parser) callonPercent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPercent1()
}

func (c *current) onBytesize1() (any, error) {
	return bytesize(c.text), nil
}

func (p *parser) callonBytesize1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBytesize1()
}

func (c *current) onDuration1() (any, error) {
	return duration(c.text), nil
}

func (p *parser) callonDuration1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDuration1()
}

func (c *current) onFloat1() (any, error) {
	return strconv.ParseFloat(string(c.text), 64)
}

func (p *parser) callonFloat1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloat1()
}

func (c *current) onInteger1() (any, error) {
	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonInteger1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onIdent2(slit any) (any, error) {
	return slit.(stringLit).string(), nil
}

func (p *parser) callonIdent2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdent2(stack["slit"])
}

func (c *current) onIdent5(slit any) (any, error) {
	return slit.(stringLit).string(), nil
}

func (p *parser) callonIdent5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdent5(stack["slit"])
}

func (c *current) onIdent8(slit any) (any, error) {
	return slit.(stringLit).string(), nil
}

func (p *parser) callonIdent8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdent8(stack["slit"])
}

func (c *current) onIdentUnquoted1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonIdentUnquoted1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentUnquoted1()
}

func (c *current) onReference1(opt, path any) (any, error) {
	err := validatePath(path.(string))
	return valueRef{path: path.(string), optional: opt != nil}, err
}

func (p *parser) callonReference1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onReference1(stack["opt"], stack["path"])
}

func (c *current) onString1(s any) (any, error) {
	return s, nil
}

func (p *parser) callonString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1(stack["s"])
}

func (c *current) onStringUnquoted1() (any, error) {
	s := string(c.text)
	return stringLit{raw: s, form: unqouted}, nil
}

func (p *parser) callonStringUnquoted1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringUnquoted1()
}

func (c *current) onStringQuoted1() (any, error) {
	s, err := strconv.Unquote(string(c.text))
	return stringLit{raw: s, form: quoted}, err
}

func (p *parser) callonStringQuoted1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringQuoted1()
}

func (c *current) onStringTripleQuoted1() (any, error) {
	s := string(bytes.Replace(c.text, []byte(`"""`), []byte(""), -1))
	return stringLit{raw: s, form: triplequoted}, nil
}

func (p *parser) callonStringTripleQuoted1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringTripleQuoted1()
}

func (c *current) onBool2() (any, error) {
	return true, nil
}

func (p *parser) callonBool2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool2()
}

func (c *current) onBool4() (any, error) {
	return false, nil
}

func (p *parser) callonBool4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool4()
}

func (c *current) onNull1() (any, error) {
	return nil, nil
}

func (p *parser) callonNull1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
