apiVersion: custom.emqx.io/v1alpha1
kind: Broker
metadata:
  name: broker-sample
spec:
  serviceAccountName: "emqx"
  image: the image of emqx
  replicas: 1
  license: the license of emqx
  storage: 
    driver: the storage driver
    server: the storage server
    accessModes: 
      - ReadWriteMany
    capacity: 10Gi
    volumeMode: Filesystem