apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-emqx-log-dir
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/tmp/emqx-log"
  nodeAffinity:
    required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname
         operator: In
         values:
         - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-emqx-data-dir
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: "/tmp/emqx-dir"
  nodeAffinity:
    required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname
         operator: In
         values:
         - docker-desktop