apiVersion: apps.emqx.io/v1beta3
kind: EmqxPlugin
metadata:
  name: emqxplugin-sample
  namespace: default
spec:
  selector:
        matchLabels:
            "apps.emqx.io/instance": "emqx"
    pluginName: fake
    config:
        "lwm2m.lifetime_min": 1s
        "lwm2m.lifetime_max": 86400s
        "lwm2m.bind.udp.1": 0.0.0.0:5683
        "lwm2m.bind.udp.2": 0.0.0.0:5683
        "lwm2m.bind.udp.3": 0.0.0.0:5683
