// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthAcl) DeepCopyInto(out *AuthAcl) {
	*out = *in
	out.AclCacheTtl = in.AclCacheTtl
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthAcl.
func (in *AuthAcl) DeepCopy() *AuthAcl {
	if in == nil {
		return nil
	}
	out := new(AuthAcl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Broker) DeepCopyInto(out *Broker) {
	*out = *in
	out.SysInterval = in.SysInterval
	out.SysHeartbeat = in.SysHeartbeat
	out.Perf = in.Perf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Broker.
func (in *Broker) DeepCopy() *Broker {
	if in == nil {
		return nil
	}
	out := new(Broker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.Autoclean = in.Autoclean
	out.DNS = in.DNS
	out.K8S = in.K8S
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNS) DeepCopyInto(out *DNS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNS.
func (in *DNS) DeepCopy() *DNS {
	if in == nil {
		return nil
	}
	out := new(DNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeflateOpts) DeepCopyInto(out *DeflateOpts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeflateOpts.
func (in *DeflateOpts) DeepCopy() *DeflateOpts {
	if in == nil {
		return nil
	}
	out := new(DeflateOpts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Emqx) DeepCopyInto(out *Emqx) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Emqx.
func (in *Emqx) DeepCopy() *Emqx {
	if in == nil {
		return nil
	}
	out := new(Emqx)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Emqx) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmqxList) DeepCopyInto(out *EmqxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Emqx, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmqxList.
func (in *EmqxList) DeepCopy() *EmqxList {
	if in == nil {
		return nil
	}
	out := new(EmqxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmqxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmqxSpec) DeepCopyInto(out *EmqxSpec) {
	*out = *in
	out.Cluster = in.Cluster
	in.Node.DeepCopyInto(&out.Node)
	in.RPC.DeepCopyInto(&out.RPC)
	in.Log.DeepCopyInto(&out.Log)
	out.AuthAcl = in.AuthAcl
	in.Mqtt.DeepCopyInto(&out.Mqtt)
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = make([]Zone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Listener != nil {
		in, out := &in.Listener, &out.Listener
		*out = make([]Listener, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Plugins = in.Plugins
	out.Broker = in.Broker
	in.Monitor.DeepCopyInto(&out.Monitor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmqxSpec.
func (in *EmqxSpec) DeepCopy() *EmqxSpec {
	if in == nil {
		return nil
	}
	out := new(EmqxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmqxStatus) DeepCopyInto(out *EmqxStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmqxStatus.
func (in *EmqxStatus) DeepCopy() *EmqxStatus {
	if in == nil {
		return nil
	}
	out := new(EmqxStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HandShakeTimeout) DeepCopyInto(out *HandShakeTimeout) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HandShakeTimeout.
func (in *HandShakeTimeout) DeepCopy() *HandShakeTimeout {
	if in == nil {
		return nil
	}
	out := new(HandShakeTimeout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8S) DeepCopyInto(out *K8S) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8S.
func (in *K8S) DeepCopy() *K8S {
	if in == nil {
		return nil
	}
	out := new(K8S)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Listener) DeepCopyInto(out *Listener) {
	*out = *in
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = make([]TCP, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = make([]SSL, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WS != nil {
		in, out := &in.WS, &out.WS
		*out = make([]WS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WSS != nil {
		in, out := &in.WSS, &out.WSS
		*out = make([]WSS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Listener.
func (in *Listener) DeepCopy() *Listener {
	if in == nil {
		return nil
	}
	out := new(Listener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerCommon) DeepCopyInto(out *ListenerCommon) {
	*out = *in
	out.RecBuf = in.RecBuf.DeepCopy()
	out.SndBuf = in.SndBuf.DeepCopy()
	out.Buffer = in.Buffer.DeepCopy()
	out.ProxyProtocolTimeout = in.ProxyProtocolTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerCommon.
func (in *ListenerCommon) DeepCopy() *ListenerCommon {
	if in == nil {
		return nil
	}
	out := new(ListenerCommon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Log) DeepCopyInto(out *Log) {
	*out = *in
	in.Rotation.DeepCopyInto(&out.Rotation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Log.
func (in *Log) DeepCopy() *Log {
	if in == nil {
		return nil
	}
	out := new(Log)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitor) DeepCopyInto(out *Monitor) {
	*out = *in
	in.SysMon.DeepCopyInto(&out.SysMon)
	in.OsMon.DeepCopyInto(&out.OsMon)
	out.VmMon = in.VmMon
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitor.
func (in *Monitor) DeepCopy() *Monitor {
	if in == nil {
		return nil
	}
	out := new(Monitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mqtt) DeepCopyInto(out *Mqtt) {
	*out = *in
	out.MaxPacketSize = in.MaxPacketSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mqtt.
func (in *Mqtt) DeepCopy() *Mqtt {
	if in == nil {
		return nil
	}
	out := new(Mqtt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Node) DeepCopyInto(out *Node) {
	*out = *in
	out.DistBufferSize = in.DistBufferSize.DeepCopy()
	out.GlobalGCInterval = in.GlobalGCInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Node.
func (in *Node) DeepCopy() *Node {
	if in == nil {
		return nil
	}
	out := new(Node)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OsMon) DeepCopyInto(out *OsMon) {
	*out = *in
	out.CpuCheckInterval = in.CpuCheckInterval
	out.MemCheckInterval = in.MemCheckInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OsMon.
func (in *OsMon) DeepCopy() *OsMon {
	if in == nil {
		return nil
	}
	out := new(OsMon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Perf) DeepCopyInto(out *Perf) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Perf.
func (in *Perf) DeepCopy() *Perf {
	if in == nil {
		return nil
	}
	out := new(Perf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Plugins) DeepCopyInto(out *Plugins) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Plugins.
func (in *Plugins) DeepCopy() *Plugins {
	if in == nil {
		return nil
	}
	out := new(Plugins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RPC) DeepCopyInto(out *RPC) {
	*out = *in
	out.ConnectTimeout = in.ConnectTimeout
	out.SendTimeout = in.SendTimeout
	out.AuthenticationTimeout = in.AuthenticationTimeout
	out.CallReceiveTimeout = in.CallReceiveTimeout
	out.SocketKeepaliveIdle = in.SocketKeepaliveIdle
	out.SocketkeepaliveInterval = in.SocketkeepaliveInterval
	out.SocketSndbuf = in.SocketSndbuf.DeepCopy()
	out.SocketRecbuf = in.SocketRecbuf.DeepCopy()
	out.SocketBuffer = in.SocketBuffer.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RPC.
func (in *RPC) DeepCopy() *RPC {
	if in == nil {
		return nil
	}
	out := new(RPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryInterval) DeepCopyInto(out *RetryInterval) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryInterval.
func (in *RetryInterval) DeepCopy() *RetryInterval {
	if in == nil {
		return nil
	}
	out := new(RetryInterval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rotation) DeepCopyInto(out *Rotation) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rotation.
func (in *Rotation) DeepCopy() *Rotation {
	if in == nil {
		return nil
	}
	out := new(Rotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSL) DeepCopyInto(out *SSL) {
	*out = *in
	in.ListenerCommon.DeepCopyInto(&out.ListenerCommon)
	out.HandShakeTimeout = in.HandShakeTimeout
	out.HighWaterMark = in.HighWaterMark.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSL.
func (in *SSL) DeepCopy() *SSL {
	if in == nil {
		return nil
	}
	out := new(SSL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SendTimeout) DeepCopyInto(out *SendTimeout) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SendTimeout.
func (in *SendTimeout) DeepCopy() *SendTimeout {
	if in == nil {
		return nil
	}
	out := new(SendTimeout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SysMon) DeepCopyInto(out *SysMon) {
	*out = *in
	out.LongGC = in.LongGC
	out.LongSchedule = in.LongSchedule
	out.LargeHeap = in.LargeHeap.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SysMon.
func (in *SysMon) DeepCopy() *SysMon {
	if in == nil {
		return nil
	}
	out := new(SysMon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCP) DeepCopyInto(out *TCP) {
	*out = *in
	in.ListenerCommon.DeepCopyInto(&out.ListenerCommon)
	out.HighWaterMark = in.HighWaterMark.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCP.
func (in *TCP) DeepCopy() *TCP {
	if in == nil {
		return nil
	}
	out := new(TCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmMon) DeepCopyInto(out *VmMon) {
	*out = *in
	out.CheckInterval = in.CheckInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmMon.
func (in *VmMon) DeepCopy() *VmMon {
	if in == nil {
		return nil
	}
	out := new(VmMon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WS) DeepCopyInto(out *WS) {
	*out = *in
	in.ListenerCommon.DeepCopyInto(&out.ListenerCommon)
	out.DeflateOpts = in.DeflateOpts
	out.IdleTimeout = in.IdleTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WS.
func (in *WS) DeepCopy() *WS {
	if in == nil {
		return nil
	}
	out := new(WS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WSS) DeepCopyInto(out *WSS) {
	*out = *in
	in.ListenerCommon.DeepCopyInto(&out.ListenerCommon)
	out.HandShakeTimeout = in.HandShakeTimeout
	out.DeflateOpts = in.DeflateOpts
	out.IdleTimeout = in.IdleTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WSS.
func (in *WSS) DeepCopy() *WSS {
	if in == nil {
		return nil
	}
	out := new(WSS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Zone) DeepCopyInto(out *Zone) {
	*out = *in
	out.IdleTimeout = in.IdleTimeout
	out.MaxPacketSize = in.MaxPacketSize.DeepCopy()
	out.KeepaliveBackoff = in.KeepaliveBackoff.DeepCopy()
	out.RetryInterval = in.RetryInterval
	out.AwaitRelTimeout = in.AwaitRelTimeout
	out.SessionExpiryInterval = in.SessionExpiryInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Zone.
func (in *Zone) DeepCopy() *Zone {
	if in == nil {
		return nil
	}
	out := new(Zone)
	in.DeepCopyInto(out)
	return out
}
