{{- if not (index .Values "admissionWebhooks" "cert" "cert-manager" "enable") -}}
{{- if .Values.admissionWebhooks.cert.certgen.enable -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "emqx-operator.fullname" . }}-conversion-patch
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "3"
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "emqx-operator.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.admissionWebhooks.conversion.patch.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "emqx-operator.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "emqx-operator.certgen.serviceAccountName" . }}
      containers:
      - name: create-secret
        image: "{{ .Values.admissionWebhooks.cert.certgen.patch.image.repository }}:{{ .Values.admissionWebhooks.cert.certgen.patch.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - create
        - --host={{ include "emqx-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc,{{ include "emqx-operator.fullname" . }}-service.{{ .Release.Namespace }}.svc.cluster.local
        - --namespace={{ .Release.Namespace }}
        - --secret-name={{  include "emqx-operator.admissionWebhooks.secretName" .}}
        - --cert-name=tls.crt
        - --key-name=tls.key
        resources:
          {{- toYaml .Values.admissionWebhooks.cert.certgen.patch.resources | nindent 12 }}
      {{- with .Values.admissionWebhooks.cert.certgen.patch.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionWebhooks.cert.certgen.patch.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionWebhooks.cert.certgen.patch.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}