{{- if not  (index .Values "admissionWebhooks" "cert" "cert-manager" "enable") -}}
{{- if .Values.admissionWebhooks.cert.certgen.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "emqx-operator.fullname" . }}-certgen-role
  labels:
    {{- include "emqx-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- with .Values.admissionWebhooks.cert.certgen.patch.serviceAccount.annotations }}
    {{- toYaml .  | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - validatingwebhookconfigurations
    - mutatingwebhookconfigurations
  verbs:
    - get
    - update
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "emqx-operator.fullname" . }}-certgen-rolebinding
  labels:
    {{- include "emqx-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- with .Values.admissionWebhooks.cert.certgen.patch.serviceAccount.annotations }}
    {{- toYaml .  | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "emqx-operator.fullname" . }}-certgen-role
subjects:
  - kind: ServiceAccount
    name: {{ include "emqx-operator.certgen.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "emqx-operator.certgen.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emqx-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- with .Values.admissionWebhooks.cert.certgen.patch.serviceAccount.annotations }}
    {{- toYaml .  | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}