name: Deployment emqx by operator
description: "Deployment emqx by operator, scale pod number, and check emqx cluster status"
inputs:
  kind:
    description: "Kind name"
    required: true
    default: "emqx"
  name:
    description: "Resource name"
    required: true
    default: "emqx"
  file:
    description: "Yaml file path"
    required: true
    default: "config/samples/emqx/v1beta3/emqx.yaml"

runs:
  using: "composite"
  steps:
    - name: Deployment emqx
      shell: bash
      run: kubectl apply -f ${{ inputs.file }}
    - name: Check emqx custom resource status
      shell: bash
      run: |
        while
          type="$(kubectl get ${{ inputs.kind }} ${{ inputs.name }} -o json |jq '.status.conditions[0] | select(.status == "True")' | jq --raw-output '.type')"
          [[ "$type" != "Ready" ]] && [[ "$type" != "Running" ]]
        do
          echo "waiting"
          sleep 1
        done
    - name: Check statefulSet doesn't update
      shell: bash
      run: |
        generation=$(kubectl get sts -l "apps.emqx.io/instance=${{ inputs.name }}" -o 'jsonpath={.items[0].status.observedGeneration}')
        if [ $generation != 1 ]; then
          kubectl get sts -l "apps.emqx.io/instance=${{ inputs.name }}" -o json
          exit 1;
        fi
