apiVersion: apps.emqx.io/v1beta4
kind: EmqxEnterprise  
metadata:
  name: emqx
  labels:
    "apps.emqx.io/instance": "emqx"
spec:
  replicas: 3
  # volumeClaimTemplates:
  #   storageClassName: standard
  #   resources:
  #     requests:
  #       storage: 20Mi
  #   accessModes:
  #     - ReadWriteOnce
  blueGreenUpdate:
    evacuationStrategy:
      waitTakeover: 200
      connEvictRate: 30
      sessEvictRate: 30
  template:
    metadata:
      labels:
        foo: bar
      annotations:
        foo: bar
    spec:
      # imagePullPolicy: [fake-secret]
      # nodeName:
      # nodeSelector:
      # affinity:
      # toleRations:
      emqxContainer:
        image: emqx/emqx-ee:4.4.8
        emqxLicense:
          # stringData:
          data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVOekNDQXgrZ0F3SUJBZ0lEZE12Vk1BMEdDU3FHU0liM0RRRUJCUVVBTUlHRE1Rc3dDUVlEVlFRR0V3SkQKVGpFUk1BOEdBMVVFQ0F3SVdtaGxhbWxoYm1jeEVUQVBCZ05WQkFjTUNFaGhibWQ2YUc5MU1Rd3dDZ1lEVlFRSwpEQU5GVFZFeEREQUtCZ05WQkFzTUEwVk5VVEVTTUJBR0ExVUVBd3dKS2k1bGJYRjRMbWx2TVI0d0hBWUpLb1pJCmh2Y05BUWtCRmc5NmFHRnVaM2RvUUdWdGNYZ3VhVzh3SGhjTk1qQXdOakl3TURNd01qVXlXaGNOTkRrd01UQXgKTURNd01qVXlXakJqTVFzd0NRWURWUVFHRXdKRFRqRVpNQmNHQTFVRUNnd1FSVTFSSUZnZ1JYWmhiSFZoZEdsdgpiakVaTUJjR0ExVUVBd3dRUlUxUklGZ2dSWFpoYkhWaGRHbHZiakVlTUJ3R0NTcUdTSWIzRFFFSkFSWVBZMjl1CmRHRmpkRUJsYlhGNExtbHZNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXJ3KzMKMnc5QjdScjNNN0lPaU1jN09EM056djJLVXd0SzZPU1EwN1k3aWtESmgwanluV2N3NlFhbVRpUldNMkFsZThqcgowWEFtS2d3VVNJNDIrZjR3ODRuUHBBSDRrMUwwenVwYVIxMFZZS0lvd1pxWFZFdlN5VjhHMk43MDkxKzZKY29uCkRjYU5CcVpMUmUxRGlaWE1KbGhYbkRncTE0RlBBeGZmS2hDWGlDZ1l0bHVMRERMS3YrdzlCYVFHWlZqeGxGZTUKY3czMit6L3hIVTM2Nm5wSEJwYWZDYnhCdFdzTnZjaE1WdExCcXY5eVBtck1xZUJST3lvSmFJM25MNzh4RGdwZApjUm9ycW8rdVExSFdkY002SW5FRkVUNnB3a2V1QUY4L2pKUmxUMTJYR2daS0tnRlFUQ2taaTRodjdheXdrR0JFCkpydVBpZi93bEswWXVQSnU2UUlEQVFBQm80SFNNSUhQTUJFR0NTc0dBUVFCZzVvZEFRUUVEQUl4TURDQmxBWUoKS3dZQkJBR0RtaDBDQklHR0RJR0RaVzF4ZUY5aVlXTnJaVzVrWDNKbFpHbHpMR1Z0Y1hoZlltRmphMlZ1WkY5dAplWE54YkN4bGJYRjRYMkpoWTJ0bGJtUmZjR2R6Y1d3c1pXMXhlRjlpWVdOclpXNWtYMjF2Ym1kdkxHVnRjWGhmClltRmphMlZ1WkY5allYTnpZU3hsYlhGNFgySnlhV1JuWlY5cllXWnJZU3hsYlhGNFgySnlhV1JuWlY5eVlXSmkKYVhRd0VBWUpLd1lCQkFHRG1oMERCQU1NQVRFd0VRWUpLd1lCQkFHRG1oMEVCQVFNQWpFd01BMEdDU3FHU0liMwpEUUVCQlFVQUE0SUJBUURIVWU2K1AyVTRqTUQyM3U5NnZ4Q2VRcmhjL3JYV3ZwbVU1WEI4US9WR25KVG12M3lVCkVQeVRGS3RFWllWWDI5ejE2eG9pcFVFNmNybEhoRVRPZmV6WXNtOUswRHhGM2ZOaWxPTFJLa2c5VkVXY2I1aGoKaUwzYTJ0ZFo0c3EraC9aMWVsSVhENzFKSkJBSW1qcjZCbGpUSWRVQ2ZWdE52eGxFOE0wRC9yS1NuMmp3enNqSQpVclc4OFRITXRsejlzYjU2a21NM0pJT29JSm9lcDZ4TkVhaklCbm9DaFNHanRCWUZORnd6ZHdTVENvZFlrZ1B1CkppZnF4VEtTdXdBR1NscXhKVXdoaldHOHVsekwzL3BDQVlFd2xXbWQyK25zZm90UWRpQU5kYVBuZXo3bzB6MHMKRXVqT0NaTWJLOHFOZlNieW81MHE1aUlYaHoyWklHbCs0aGRwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        emqxConfig:
          name: emqx
          cluster.discovery: dns
          cluster.dns.type: srv
          cluster.dns.app: emqx
          cluster.dns.name: emqx-headless.default.svc.cluster.local
          listener.tcp.external: "1883"
        emqxACL:
          - "{allow, all}."
      # extraContainers:
      #   - name: extra
      #     image: busybox:stable
      #     command:
      #       - /bin/sh
      #       - -c
      #       - |
      #         tail -f /dev/null
      # initContainers:
      #   - name: busybox
      #     image: busybox:stable
      #     securityContext:
      #       runAsUser: 0
      #       runAsGroup: 0
      #       capabilities:
      #         add:
      #         - SYS_ADMIN
      #         drop:
      #         - ALL
      #     command:
      #       - /bin/sh
      #       - -c
      #       - |
      #         mount -o remount rw /proc/sys
      #         sysctl -w net.core.somaxconn=65535
      #         sysctl -w net.ipv4.ip_local_port_range="1024 65535"
      #         sysctl -w kernel.core_uses_pid=0
      #         sysctl -w net.ipv4.tcp_tw_reuse=1
      #         sysctl -w fs.nr_open=1000000000
      #         sysctl -w fs.file-max=1000000000
      #         sysctl -w net.ipv4.ip_local_port_range='1025 65534'
      #         sysctl -w net.ipv4.udp_mem='74583000 499445000 749166000'
      #         sysctl -w net.ipv4.tcp_max_sync_backlog=163840
      #         sysctl -w net.core.netdev_max_backlog=163840
      #         sysctl -w net.core.optmem_max=16777216
      #         sysctl -w net.ipv4.tcp_rmem='1024 4096 16777216'
      #         sysctl -w net.ipv4.tcp_wmem='1024 4096 16777216'
      #         sysctl -w net.ipv4.tcp_max_tw_buckets=1048576
      #         sysctl -w net.ipv4.tcp_fin_timeout=15
      #         sysctl -w net.core.rmem_default=262144000
      #         sysctl -w net.core.wmem_default=262144000
      #         sysctl -w net.core.rmem_max=262144000
      #         sysctl -w net.core.wmem_max=262144000
      #         sysctl -w net.ipv4.tcp_mem='378150000  504200000  756300000'
      #         sysctl -w net.netfilter.nf_conntrack_max=1000000
      #         sysctl -w net.netfilter.nf_conntrack_tcp_timeout_time_wait=30

  serviceTemplate:
    metadata:
      name: emqx
      namespace: default
      labels:
        "apps.emqx.io/instance": "emqx"
    spec:
      type: NodePort
      selector:
        "apps.emqx.io/instance": "emqx"
      ports:
        - name: "http-management-8081"
          port: 8081
          protocol: "TCP"
          targetPort: 8081
        - name: "http-dashboard-18083"
          port: 18083
          protocol: "TCP"
          targetPort: 18083
          nodePort: 30648
        - name: "mqtt-tcp-1883"
          protocol: "TCP"
          port: 1883
          targetPort: 1883
          nodePort: 30649
        - name: "mqtt-tcp-11883"
          protocol: "TCP"
          port: 11883
          targetPort: 11883
          nodePort: 30650
        - name: "mqtt-ws-8083"
          protocol: "TCP"
          port: 8083
          targetPort: 8083
          nodePort: 30651
        - name: "mqtt-wss-8084"
          protocol: "TCP"
          port: 8084
          targetPort: 8084
          nodePort: 30652