apiVersion: apps.emqx.io/v1beta4
kind: EmqxRebalance
metadata:
  name: emqxrebalance-sample
spec:
  emqxInstance: emqx-ee
  rebalanceStrategy:
    connEvictRate: 10
    sessEvictRate: 10
    waitTakeover: 10
    waitHealthCheck: 0 
    absConnThreshold: 100
    relConnThreshold: "1.2"
    absSessThreshold: 100
    relSessThreshold: "1.2"
