resources:
- bases/apps.emqx.io_emqxes.yaml
- bases/apps.emqx.io_rebalances.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
- path: ./compat/v2beta1_patch.yaml
  target:
    kind: CustomResourceDefinition
    name: emqxes.apps.emqx.io
