apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
  name: emqx
  labels:
    "apps.emqx.io/instance": "emqx"
spec:
  coreTemplate:
    metadata:
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: core
      annotations:
    spec:
      replicas: 3
      image: "emqx/emqx:5.0.3"

  replicantTemplate:
    metadata:
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: replicant
    spec:
      replicas: 5
      image: "emqx/emqx:5.0.3"