apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
  name: emqx
  labels:
    "apps.emqx.io/instance": "emqx"
spec:
  image: "emqx/emqx:5.0.5"
  coreTemplate:
    metadata:
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: core
      annotations:
    spec:
      replicas: 3
  replicantTemplate:
    metadata:
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: replicant
    spec:
      replicas: 0