apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs: 
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - events
  - secrets
  - events
  - services
  - persistentvolumes
  - persistentvolumeclaims
  verbs: 
  - "*"
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxes/finalizers
  verbs:
  - update
- apiGroups:
  - apps.emqx.io
  resources:
  - emqxes/status
  verbs:
  - get
  - patch
  - update
